image: fedora:rawhide

variables:
  DEPENDENCIES: gcc
                gcovr
                pkgconfig(udev)
                pkgconfig(systemd)
                pkgconfig(gio-2.0)
                pkgconfig(gudev-1.0)
                pkgconfig(upower-glib)
                pkgconfig(polkit-gobject-1)
                systemd
                meson
                git
                python3-packaging
  TEST_DEPENDENCIES: e2fsprogs
                     python3-dbusmock
                     python3-gobject
                     python3-pylint
                     umockdev

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

.install-deps:
  variables:
    TMPDIR: $CI_BUILDS_DIR/tmpdir
  before_script:
    - echo 8096000 > /proc/sys/fs/inotify/max_user_instances
    - mkdir -m 700 $TMPDIR -p
    - dnf update -y
    - if [ -x /bin/dnf ]; then
        dnf install -y $DEPENDENCIES $JOB_DEPS;
      else
        dnf5 install -y $DEPENDENCIES $JOB_DEPS;
      fi

pre_commit:
  variables:
    DEPENDENCIES: {}
    JOB_DEPS: pre-commit
              git
  extends:
    - .install-deps
  script:
    - pre-commit run --all-files

build_stable:
  variables:
    JOB_DEPS: $TEST_DEPENDENCIES
              argparse-manpage
              python3-shtab
  extends:
    - .install-deps
  script:
    - meson setup
        --werror
        --fatal-meson-warnings
        --warnlevel 2
        -Dpylint=enabled
        -Dmanpage=enabled
        -Db_coverage=true
        _build
    - meson test -C _build --print-errorlogs
    - .ci/fail_skipped_tests.py _build/meson-logs/testlog.junit.xml
    - ninja -C _build coverage
    - cat _build/meson-logs/coverage.txt || true
    - meson install -C _build
    - ninja -C _build uninstall -v
    - meson dist -C _build
  artifacts:
    when: always
    paths:
    - _build/meson-logs/*.txt
    - _build/meson-dist/*
    - _build/meson-logs/coveragereport/*
    reports:
      junit:
        - _build/meson-logs/testlog.junit.xml
      coverage_report:
        coverage_format: cobertura
        path: _build/meson-logs/coverage.xml
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

address_sanitizer:
  variables:
    JOB_DEPS: $TEST_DEPENDENCIES
              libasan
              libubsan
  extends:
    - .install-deps
  script:
    - meson setup
        --werror
        --buildtype=debug
        _build
        -Db_sanitize=address,undefined
    - meson test -C _build --print-errorlogs -t 3
  artifacts:
    when: on_failure
    paths:
    - _build/meson-logs/*.txt

valgrind:
  variables:
    JOB_DEPS: $TEST_DEPENDENCIES
              valgrind
  extends:
    - .install-deps
  script:
    - meson setup
        --werror
        --buildtype=debug
        _build
    - meson test -C _build --print-errorlogs --setup=valgrind
  artifacts:
    when: on_failure
    paths:
    - _build/meson-logs/*.txt

scan_build:
  variables:
    JOB_DEPS: clang-analyzer
              which
  extends:
    - .install-deps
  script:
    - meson setup _build -Dtests=false
    - env SCANBUILD=$(which scan-build) ninja -C _build scan-build
  artifacts:
    when: on_failure
    paths:
      - _build/meson-logs

docs:
  variables:
    JOB_DEPS: gtk-doc
  extends:
    - .install-deps
  script:
    - meson setup
        -Dgtk_doc=true
        -Dtests=false
        _build-docs
    - ninja -C _build-docs power-profiles-daemon-doc
  artifacts:
    expose_as: "HTML Documentation"
    paths:
    - _build-docs/docs/html
    - _build-docs/docs/html/index.html
    expire_in: 1 week
