image: fedora:rawhide

variables:
  DEPENDENCIES: gcc
                gtk-doc
                pkgconfig(udev)
                pkgconfig(systemd)
                pkgconfig(gio-2.0)
                pkgconfig(gudev-1.0)
                pkgconfig(upower-glib)
                pkgconfig(polkit-gobject-1)
                systemd
                meson
                git
                python3-gobject
                python3-dbusmock
                python3-packaging
                python3-pylint
                umockdev
                e2fsprogs

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

build_stable:
  before_script:
    - dnf update -y
    - if [ -x /bin/dnf ]; then dnf install -y $DEPENDENCIES; else dnf5 install -y $DEPENDENCIES; fi
    - mkdir tmpdir/
  script:
    - meson setup
        -Dgtk_doc=true
        -Dpylint=true
        -Dtests=true
        _build
    - env TMPDIR=$(pwd)/tmpdir meson test -C _build --print-errorlogs
    - .ci/fail_skipped_tests.py _build/meson-logs/testlog.junit.xml
    - meson install -C _build
    - ninja -C _build uninstall -v
    - TMPDIR=$(pwd)/tmpdir ninja -v -C _build dist
  artifacts:
    when: always
    paths:
    - _build/meson-logs/*.txt
    - _build/meson-dist/*
    reports:
      junit:
        - _build/meson-logs/testlog.junit.xml
