image: fedora:rawhide

variables:
  DEPENDENCIES: gcc
                gcovr
                gtk-doc
                pkgconfig(udev)
                pkgconfig(systemd)
                pkgconfig(gio-2.0)
                pkgconfig(gudev-1.0)
                pkgconfig(upower-glib)
                pkgconfig(polkit-gobject-1)
                systemd
                meson
                git
                python3-gobject
                python3-dbusmock
                python3-packaging
                python3-pylint
                umockdev
                e2fsprogs

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

.install-deps:
  before_script:
    - dnf update -y
    - if [ -x /bin/dnf ]; then dnf install -y $DEPENDENCIES $JOB_DEPS; else dnf5 install -y $DEPENDENCIES $JOB_DEPS; fi

pre_commit:
  variables:
    DEPENDENCIES: {}
    JOB_DEPS: pre-commit
              git
  extends:
    - .install-deps
  script:
    - pre-commit run --all-files

build_stable:
  extends:
    - .install-deps
  script:
    - mkdir tmpdir/
    - meson setup
        --werror
        --fatal-meson-warnings
        --warnlevel 2
        -Dgtk_doc=true
        -Dpylint=true
        -Db_coverage=true
        _build
    - env TMPDIR=$(pwd)/tmpdir meson test -C _build --print-errorlogs
    - .ci/fail_skipped_tests.py _build/meson-logs/testlog.junit.xml
    - ninja -C _build coverage
    - cat _build/meson-logs/coverage.txt || true
    - meson install -C _build
    - ninja -C _build uninstall -v
    - TMPDIR=$(pwd)/tmpdir ninja -v -C _build dist
  artifacts:
    when: always
    paths:
    - _build/meson-logs/*.txt
    - _build/meson-dist/*
    reports:
      junit:
        - _build/meson-logs/testlog.junit.xml
      coverage_report:
        coverage_format: cobertura
        path: _build/meson-logs/coverage.xml
  coverage: '/^TOTAL.*\s+(\d+\%)$/'

scan_build:
  variables:
    JOB_DEPS: clang-analyzer
  extends:
    - .install-deps
  script:
    - meson setup _build
    -  env SCANBUILD=$(which scan-build) ninja -C _build scan-build
  artifacts:
    when: on_failure
    paths:
      - _build/meson-logs
